worker_processes auto;

error_log /var/log/angie/error.log info;
pid /run/angie.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/angie/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/angie/access.log main;
    sendfile on;
    keepalive_timeout 65;

    # Required for ACME client operation.
    resolver 1.1.1.1 8.8.8.8 ipv6=off valid=300s;

    # Native Angie ACME client (Let's Encrypt production directory).
    acme_client le https://acme-v02.api.letsencrypt.org/directory;

    include /etc/angie/http.d/*.conf;
}
