services:
  angie:
    image: docker.angie.software/angie:latest
    container_name: angie
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./angie.conf:/etc/angie/angie.conf:ro
      - ./certs:/etc/angie/certs:ro
      - ./http.d:/etc/angie/http.d
      - ./acme:/var/lib/angie/acme

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
