server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate     /etc/angie/certs/default.crt;
    ssl_certificate_key /etc/angie/certs/default.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    return 444;
}

server {
    listen 80;
    server_name kostjaz.ru qnap.kostjaz.ru argocd.kostjaz.ru;

    acme le;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name kostjaz.ru;

    acme le;

    ssl_certificate     $acme_cert_le;
    ssl_certificate_key $acme_cert_key_le;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location / {
        include /etc/angie/http.d/proxy.conf;
        proxy_pass http://192.168.133.64;
    }
}

server {
    listen 443 ssl;
    server_name qnap.kostjaz.ru;

    acme le;

    ssl_certificate     $acme_cert_le;
    ssl_certificate_key $acme_cert_key_le;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location / {
        include /etc/angie/http.d/proxy.conf;
        proxy_pass http://192.168.133.2:8080;
    }
}

server {
    listen 443 ssl;
    server_name argocd.kostjaz.ru;

    acme le;

    ssl_certificate     $acme_cert_le;
    ssl_certificate_key $acme_cert_key_le;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location / {
        include /etc/angie/http.d/proxy.conf;
        proxy_pass http://192.168.133.64;
    }
}
